### ISSUE TITLE
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by emres** [microsoftgraph/python-sample-send-mail#3]
When I run the sample application in a PowerShell (run as Administrator), I received the following error:

```
(meetingStats) PS C:\Documents\code\meetingStats> python .\sample.py
Traceback (most recent call last):
  File ".\sample.py", line 260, in <module>
    APP.run()
  File "C:\Documents\code\meetingStats\lib\site-packages\flask\app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "C:\Documents\code\meetingStats\lib\site-packages\werkzeug\serving.py", line 795, in run_simple
    s.bind(get_sockaddr(hostname, port, address_family))
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```
This might be caused by some other program using the **default** Flask app port of **5000**. When I change the the final line at https://github.com/microsoftgraph/python-sample-send-mail/blob/b2995415969c99abf3b4966d334ca7b910351857/sample.py#L260 to:

`APP.run(port=9999)`

but then of course, after successful authentication, it (via Flask) tries to redirect to the default port of **5000**, and when I change **5000** to **9999** in the URL in my browser and hit enter, it works correctly, shows me the email sending screen, etc.

Should I update README? But this would be half-baked solution, do you know how to tell Flask to not to redirect to 5000 again? Because obviously `APP.run(port=9999)` leads to problems again, which can be very disappointing for people who are just getting started.

**Comment by emres** [comment]
There was some discussion at StackOverflow: https://stackoverflow.com/q/48682476/236007

Updating README about this pitfall would be very useful. I'll see if I can send a pull request to README later.

**Comment by sunilbainsla** [comment]
It was happening for me because Pycharam is already using the default port 5000. While running the flask app I added different port like flask run -p 9999 and it worked for me

**Comment by jasonjoh** [comment]
@emres we are archiving this sample as it's no longer being maintained. We're replacing it with https://github.com/microsoftgraph/msgraph-training-pythondjangoapp.
