### ISSUE TITLE
Regarding listing calendar events

### ISSUE THREAD

**Issue by iniyanp** [microsoftgraph/python-sample-send-mail#4]
Hi,

I am trying to hit this api `me/calendars` in the same code base. It's not working.

I am getting this following response.
```
{
error: {
code: "ErrorAccessDenied",
message: "Access is denied. Check credentials and try again.",
innerError: {
request-id: "7ba3122c-5c9f-42f9-b65e-ba01724bca67",
date: "2018-02-14T00:30:48"
}
}
}
```
 even though I am sending access token in the header.

When I hit this `me/microsoft.graph.sendMail` endpoint, it's working.

Please let me know what I am missing.

Thanks,
Iniyan P

**Comment by dmahugh** [comment]
Hey Iniyan, just saw your comment. Did you get this working? From the error message you show, I think the issue may be that you need to register the app with a delegated permission of **Calendar.Read** (which the send-mail sample doesn't include).

**Comment by jasonjoh** [comment]
@iniyanp we are archiving this sample as it's no longer being maintained. We're replacing it with https://github.com/microsoftgraph/msgraph-training-pythondjangoapp.
