### ISSUE TITLE
Handle case when content_type is emty

### ISSUE THREAD

**Issue by thoth291** [microsoftgraph/python-sample-send-mail#5]
My profile had a photo - but not content type (for some reason).
So I had to modify this line:
https://github.com/microsoftgraph/python-sample-send-mail/blob/b2995415969c99abf3b4966d334ca7b910351857/sample.py#L147
Like this:
```python
if content_type:
    extension = content_type.split('/')[1]
else:
    extension = 'jpeg'
```

**Comment by jasonjoh** [comment]
@thoth291 we are archiving this sample as it's no longer being maintained. We're replacing it with https://github.com/microsoftgraph/msgraph-training-pythondjangoapp.
